################################################################################
# Main vars for ETL
################################################################################

# Server name prefix
server_prefix: dcc
dcc_user: dcc_dev
dcc_user_directory: "/u/{{dcc_user}}"

# Directories
staging_dir: /tmp


################################################################################
# DCC Resources, DCC Dependices
################################################################################

# DCC apt proxy.
proxy_env:
  http_proxy: ***REMOVED***

# External URLs 
external_submission_url: http://hwww2-dcc.oicr.on.ca:5380
external_docs_url: http://docs.icgc.org

# Artifactory URLS
artifactory_url: http://seqwaremaven.oicr.on.ca/artifactory
artifactory_release_url: "{{ artifactory_url }}/dcc-release" 
artifactory_deps_url: "{{ artifactory_url }}/simple/dcc-dependencies" 
artifactory_release_url: "{{ artifactory_url }}/simple/dcc-release"
artifactory_snapshot_url: "{{ artifactory_url }}/simple/dcc-snapshot"

# Reference Genome
reference_genome_name: dcc-reference-genome
reference_genome_basename: GRCh37
reference_genome_version: 75.v1
reference_genome_filename: "{{ reference_genome_basename}}.{{ reference_genome_version }}"
reference_genome_archive: "{{ reference_genome_name }}-{{ reference_genome_filename }}.tar.gz"
reference_genome_url: "{{ artifactory_deps_url }}/org/icgc/dcc/{{ reference_genome_name }}/{{ reference_genome_filename }}/{{ reference_genome_archive }}"

dcc_etl_cli_jar: "{{ artifactory_snapshot_url }}/org/icgc/dcc/dcc-etl-cli/3.5.11-SNAPSHOT/dcc-etl-cli-3.5.11-SNAPSHOT.jar"
dcc_submission_server_jar: "{{ artifactory_snapshot_url }}/org/icgc/dcc/dcc-submission-server/3.5.11-SNAPSHOT/dcc-submission-server-3.5.11-SNAPSHOT.jar"
dcc_submission_server_tarball_artifactory_url: "{{ artifactory_snapshot_url }}/org/icgc/dcc/dcc-submission-server/3.5.11-SNAPSHOT/dcc-submission-server-3.5.11-SNAPSHOT-dist.tar.gz"
dcc_downloader_tarball: "{{ artifactory_snapshot_url }}/org/icgc/dcc/dcc-downloader/3.6.1.2-SNAPSHOT/dcc-downloader-3.6.1.2-SNAPSHOT-dist.tar.gz"

# Hadoop Settings
fs_url: "hdfs://{{ server_prefix }}-hadoop-worker-1"
job_tracker: "{{ server_prefix }}-hadoop-worker-1:8021"
name_node_host: "{{ server_prefix }}-hadoop-worker-1"
name_node: "hdfs://{{ server_prefix }}-hadoop-worker-1:8020"
zookeeper_quorum: "{{ server_prefix }}-hadoop-worker-1"
hadoop_username: hdfs

postgresql_user: dcc
postgresql_password: dcc
postgresql_uri: "jdbc:postgresql://{{ server_prefix }}-postgres"
fathmm_uri: "{{ postgresql_uri }}/fathmm?user={{postgresql_user}}&password={{postgresql_password}}"
mongo_base_uri: "mongodb://{{ server_prefix }}-mongo"
identifier_uri: "http://{{ server_prefix }}-identifier:6381"
elasticsearch_uri: "es://{{ server_prefix }}-elasticsearch:9300"
mongo_host: "{{ server_prefix }}-mongo"


