################################################################################
# Main vars for ETL
################################################################################

# Server name prefix
server_prefix: dcc

# Username and directory
dcc_user: dcc_dev
dcc_user_directory: "/u/{{dcc_user}}"

# Some etl settings shared between roles.
etl_root_dir: "{{ dcc_user_directory }}/dcc-etl"
data_dir: "{{ etl_root_dir }}/data"
repo_dir: "{{ etl_root_dir }}/git/dcc-etl"

# Directories
staging_dir: /tmp


# versions
ditionary_version: 0.10a


################################################################################
# DCC Resources, DCC Dependices
################################################################################

# DCC apt proxy.
proxy_env:
  http_proxy: ***REMOVED***

# External URLs 
external_submission_url: http://hwww2-dcc.oicr.on.ca:5380
external_docs_url: http://docs.icgc.org

# Submission Server
submission_server_dist_name: dcc-submission-server
submission_server_dist_version: 3.7.4.1
submission_server_dist_filename: "{{ submission_server_dist_name }}-{{ submission_server_dist_version }}-dist.tar.gz"
submission_server_jar_filename: "{{ submission_server_dist_name }}-{{ submission_server_dist_version }}.jar"
submission_server_dist_url: "{{ artifactory_release_url }}/org/icgc/dcc/{{ submission_server_dist_name }}/{{ submission_server_dist_version }}/{{ submission_server_dist_filename }}"
submission_server_jar_url: "{{ artifactory_release_url }}/org/icgc/dcc/{{ submission_server_dist_name }}/{{ submission_server_dist_version }}/{{ submission_server_jar_filename }}"

# Artifactory URLS
artifactory_url: http://seqwaremaven.oicr.on.ca/artifactory
artifactory_release_url: "{{ artifactory_url }}/dcc-release" 
artifactory_deps_url: "{{ artifactory_url }}/simple/dcc-dependencies" 
artifactory_release_url: "{{ artifactory_url }}/simple/dcc-release"
artifactory_snapshot_url: "{{ artifactory_url }}/simple/dcc-snapshot"

# Reference Genome
reference_genome_name: dcc-reference-genome
reference_genome_basename: GRCh37
reference_genome_version: 75.v1
reference_genome_filename: "{{ reference_genome_basename}}.{{ reference_genome_version }}"
reference_genome_archive: "{{ reference_genome_name }}-{{ reference_genome_filename }}.tar.gz"
reference_genome_url: "{{ artifactory_deps_url }}/org/icgc/dcc/{{ reference_genome_name }}/{{ reference_genome_filename }}/{{ reference_genome_archive }}"

# Hadoop Settings
hadoop_fs_url: "hdfs://{{ server_prefix }}-hadoop-worker-1"
hadoop_job_tracker: "{{ server_prefix }}-hadoop-worker-1:8021"
hadoop_name_node_host: "{{ server_prefix }}-hadoop-worker-1"
hadoop_name_node: "hdfs://{{ server_prefix }}-hadoop-worker-1:8020"
hadoop_zookeeper_quorum: "{{ server_prefix }}-hadoop-worker-1"
hadoop_username: hdfs
fuse_root_dir: /hdfs/dcc

postgresql_user: dcc
postgresql_password: dcc
postgresql_uri: "jdbc:postgresql://{{ server_prefix }}-postgres"
fathmm_uri: "{{ postgresql_uri }}/fathmm?user={{postgresql_user}}&password={{postgresql_password}}"
mongo_base_uri: "mongodb://{{ server_prefix }}-mongo"
identifier_uri: "http://{{ server_prefix }}-identifier:6381"
elasticsearch_uri: "es://{{ server_prefix }}-elasticsearch:9300"
mongo_host: "{{ server_prefix }}-mongo"


