# Copyright 2015(c) The Ontario Institute for Cancer Research. All rights reserved.

- name: Create file system
  file: "path={{ item }} state=directory"
  with_items:
    - "{{ install_dir }}"

- name: Download the distribution
  get_url: "url={{ identifier_dist_url }} dest={{ staging_dir }}/{{ identifier_dist_archive }} mode=0444"


- name: Extract the dist 
  command: "tar xzf {{ staging_dir }}/{{ identifier_dist_archive }} --strip 1 -C {{ install_dir }}" 
  sudo: yes

# Configure the application
- name: Configure application
  template: src=settings.yml.j2 dest="{{ conf_dir }}/settings.yml"


# Install and start service
- name: Install service
  command: "{{ bin_dir }}/{{ identifier_installer_name }} install creates=/etc/init.d/{{ identifier_dist_name }}"
  
- name: Ensure daemon is running
  service: name={{ identifier_dist_name }} state=started



