- name: Clean copy
  file: path="{{ install_dir }}"
        state=absent

- name: Ensure directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ install_dir }}"

- name: Download the distribution
  get_url:  url="{{ portal_dist_url }}"
            dest="{{ staging_dir }}/{{ portal_dist_filename }}"
            mode=0444

- name: Extract the dist
  unarchive:  src="{{ staging_dir }}/{{ portal_dist_filename }}"
              dest="{{ install_dir }}"
              copy=no

- name: Update the symbolic link to the distribution
  file: path="{{ portal_root }}"
        src="{{ install_dir }}/{{ portal_dist_fullname }}"
        state=link
        force=yes

- name: Ensure directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ portal_conf }}"

- name: Copy over portal configuraiton file
  template: src="settings.yml.j2" dest="{{ portal_conf }}/settings.yml" mode=644 force=yes

- name: Start dcc-portal
  shell: "{{ portal_root }}/bin/dcc-portal-api restart"
