- name: Ensure directories
  file: "path={{ item }} state=directory"
  with_items:
    - "{{ install_dir }}"
    - "{{ conf_dir }}"

- name: Download the distribution
  get_url: "url={{ portal_dist_url }} dest={{ staging_dir }}/{{ portal_dist_archive }} mode=0444"

- name: Extract the dist 
  command: "tar xzf {{ staging_dir }}/{{ portal_dist_archive }} -C {{ install_dir }}" 

- name: Copy over portal configuraiton file
  template: src="settings.yml.j2" dest="{{ conf_dir }}/settings.yml" mode=644 force=yes

- name: Start dcc-portal
  shell: "{{ install_dir }}/dcc-portal-api-{{ portal_dist_version }}/bin/dcc-portal-api restart"



