---

- name: Update apt-get 
  apt:  update_cache=yes
- name: install python-apt
  raw:  "apt-get install -y python-apt"
- name: install ntp
  apt:  pkg=ntp 
        state=latest
  notify: start ntp    
- name: Install apt packages
  apt:  pkg={{ item }}
        state=latest
  with_items:
    - sudo
    - tree
    - curl
- name: get ClouderaManager repo list
  shell: curl http://archive.cloudera.com/cm5/ubuntu/precise/amd64/cm/cloudera.list >> /etc/apt/sources.list.d/cloudera.list
- name: update the repositories
  apt: update_cache=yes
