# Copyright 2015(c) The Ontario Institute for Cancer Research. All rights reserved.

- name: Update apt-get 
  apt:  update_cache=yes

- name: Install python-apt
  raw:  "apt-get install -y python-apt"

- name: Install ntp
  apt:  pkg=ntp 
        state=latest
  notify: start ntp    

- name: Install apt packages
  apt:  pkg={{ item }}
        state=latest
        force=yes
  with_items:
    - sudo
    - tree
    - curl

- name: Copy over Cloudera Manager repo list
  template: src="cloudera.list.j2" dest="/etc/apt/sources.list.d/cloudera.list" mode=644 force=yes

- name: Update the repositories
  apt: update_cache=yes
