---

- name: Check CM service existence and state
  command:  service cloudera-scm-server status
  register: cm_started
  ignore_errors: yes

- include: installer.yml
  when: cm_started.stdout.find('cloudera-scm-server is running') == -1

- name: Wait for ssh
  wait_for: host={{ inventory_hostname }}
            port=7180
            timeout=30
  delegate_to: localhost
