---

- name: Check CM service existence and state
  command:  service cloudera-scm-server status
  register: cm_started
  ignore_errors: yes

- include: installer.yml
  when: cm_started.stdout.find('cloudera-scm-server is running') == -1

- name: wait for Cloudera Manager web interface to become available
  wait_for: port=8000 delay=30
