- name: Install ACL
  apt: pkg={{ item }}
       state=present
  with_items:
    - acl

- name: Install Hadoop MapReduce Task Tracker
  apt: pkg=hadoop-0.20-mapreduce-tasktracker
       state=present

- name: Configure Job Tracker
  template: src={{ item }}.xml.j2 dest={{ conf_dir }}/mapred-site.xml
  with_items:
    - mapred-site.tasktracker
  notify:
    - Restart Task Tracker