- name: Clean copy
  file: path="{{ annotator_root }}"
        state=absent

- name: Create directories
  file: path="{{ item }}" 
        state="directory" 
        owner="{{ dcc_user }}"
  with_items:
    - "{{ dcc_user_directory }}"
    - "{{ annotator_root }}"

- name: get dcc-annotator tarball from artifactory
  get_url:  url="{{ annotator_dist_url }}" 
            dest="{{ staging_dir }}/{{ annotator_dist_filename }}" 
            mode=644

- name: Extract dcc-annotator ==> /u/dcc_dev/dcc_annotator
  unarchive:  src="{{ staging_dir }}/{{ annotator_dist_filename }}"
              dest="{{ annotator_root }}"
              copy=no

- name: Copy over annotator configuration
  template: src="annotator.yml.j2" 
            dest="{{ annotator_root }}/conf/annotator.yml" 
            mode=0755

- name: Make sure dcc_dev owns everything
  file: path="{{ annotator_root }}" 
        owner={{ dcc_user }}
        recusre=yes
