- name: Clean copy
  file: path="{{ annotator_root }}"
        state=absent

- name: get dcc-annotator tarball from artifactory
  get_url:  url="{{ annotator_dist_url }}" 
            dest="{{ staging_dir }}/{{ annotator_dist_filename }}" 
            mode=644

- name: Extract dcc-annotator ==> /u/dcc_dev/dcc_annotator
  unarchive:  src="{{ staging_dir }}/{{ annotator_dist_filename }}"
              dest="{{ dcc_home }}"
              copy=no

- name: Update the symbolic link to the distribution
  file: path="{{ annotator_root }}"
        src="{{ dcc_home }}/{{ annotator_dist_fullname }}"
        state=link 
        owner="{{ dcc_user }}"
        force=yes

- name: Create directories
  file: path="{{ item }}" 
        state="directory" 
        owner="{{ dcc_user }}"
  with_items:
    - "{{ annotator_conf }}"

- name: Copy over annotator configuration
  template: src="annotator.yml.j2" 
            dest="{{ annotator_conf }}/annotator.yml" 
            mode=0755

# https://github.com/ansible/ansible/issues/548
- name: Make sure dcc_dev owns everything
  file: path="{{ dcc_home }}" 
        owner={{ dcc_user }}
        recurse=yes
