# Copyright 2015(c) The Ontario Institute for Cancer Research. All rights reserved.

exporter_name: dcc-exporter
exporter_home: "{{ dcc_home }}/{{ exporter_name }}"
exporter_log: "{{ exporter_home }}/logs"

exporter_dist_name: dcc-etl-exporter
exporter_dist_fullname: "{{ exporter_dist_name }}-{{ exporter_dist_version }}"
exporter_dist_filename: "{{ exporter_dist_fullname }}-dist.tar.gz"

exporter_dist_url: "{{ artifactory_snapshot_url }}/{{ artifactory_dcc_path }}/{{exporter_dist_name}}/{{exporter_dist_version}}/{{exporter_dist_filename}}"
