- name: Setting up Cloudera Manager
  hosts: manager
  sudo: True
  gather_facts: False
  vars_files:
    - "vars/main.yml"
  tasks:
    - name: Setup CDH repositories
      include: install-cdh-repository.yml
    - name: Update apt-get 
      apt:  update_cache=yes
    - name: install python-apt
      raw:  "apt-get install -y python-apt"
    - name: install ntp
      apt:  pkg=ntp 
            state=latest
      notify: start ntp    
    - name: Install apt packages
      apt:  pkg={{ item }}
            state=latest
      with_items:
        - sudo
        - tree
        - curl
    - name: Install Java
      include: tasks/install-java.yml
    - name: Install Cloudera Manager Server
      action: apt pkg={{ item }} state=latest
      with_items:
        - cloudera-manager-daemons
        - cloudera-manager-server-db
        - cloudera-manager-server
    - name: Start CM services
      service:  name={{ item }}
                state=running
      with_items:
        - cloudera-scm-server-db
        - cloudera-scm-server
  handlers:
    - name: start ntp
      service:  name=ntp 
                state=started
  tags:
    - provision
