- name: Clean copy
  file: path="{{ exporter_root }}"
        state=absent

- name: get exporter tarball from artifactory
  get_url:  url="{{ exporter_dist_url }}" 
            dest="{{ staging_dir }}/{{ exporter_dist_filename }}" 
            mode=644

- name: Extract dcc-exporter
  unarchive:  src="{{ staging_dir }}/{{ exporter_dist_filename }}"
              dest="{{ dcc_user_directory }}"
              copy=no

- name: Update the symbolic link to the distribution
  file: path="{{ exporter_root }}"
        src="{{ dcc_user_directory }}/{{ exporter_dist_fullname }}"
        state=link 
        force=yes

- name: Create directories
  file: path="{{ item }}" 
        state="directory" 
        owner="{{ dcc_user }}"
  with_items:
    - "{{ exporter_root }}/logs"

# Make up HDFS directories 
- name: Make downloader directory
  shell: "HADOOP_USER_NAME=hdfs hadoop fs -mkdir /user/downloader"
  ignore_errors: yes

- name: Give downloader ownership
  shell: "HADOOP_USER_NAME=hdfs hadoop fs -chown -R downloader /user/downloader"
  ignore_errors: yes

# Patch overarching script FIXME: should be parameterized in overarch
- name: Patch export facade
  lineinfile: dest="{{ repo_dir }}/dcc-etl-cli/src/main/scripts/overarch/facades/exporter-facade.sh" 
              regexp="^exporter_bin_dir" 
              line="exporter_bin_dir={{ exporter_root }}/bin"

# Patch configurations: FIXME: should be parameterized in overarch
- name: Patch zookeeper location
  lineinfile: dest="{{ exporter_root }}/scripts/pig/bucket.pig" 
              regexp="^set hbase.zookeeper.quorum" 
              line="set hbase.zookeeper.quorum '{{ hadoop_zookeeper_quorum }}'"
  ignore_errors: yes

- name: Patch zookeeper location
  lineinfile: dest="{{ exporter_root }}/scripts/core.py" 
              regexp="hbase.zookeeper.quorum" 
              line="Pig.set('hbase.zookeeper.quorum', '{{ hadoop_zookeeper_quorum }}')"
  ignore_errors: yes

# Patch environment: FIXME: should probably be parameterized by overarch
- name: Patch setenv
  lineinfile: dest="{{ exporter_root }}/bin/setenv.sh" 
              regexp="^export HBASE_CONF_DIR" 
              line="export HBASE_CONF_DIR=/etc/hbase/conf"
  ignore_errors: yes

# https://github.com/ansible/ansible/issues/548
- name: Make sure dcc_dev owns everything
  file: path="{{ dcc_user_directory }}" 
        owner={{ dcc_user }}
        recurse=yes
