# Copyright 2016(c) The Ontario Institute for Cancer Research. All rights reserved.

hdfs_cloudera_distribution: "cdh5.3.1"
hdfs_conf_dir: "/etc/hadoop/conf"
hdfs_namenode: False
hdfs_namenode_host: dcc-hadoop-master
hdfs_namenode_port: 8020
hdfs_disks: [{ mount_point: '/dfs/data', device: '/dev/sda1' }]

hdfs_core_properties:
  - { name: "fs.defaultFS", value: "hdfs://{{ hdfs_namenode_host }}:{{ hdfs_namenode_port }}" }
hdfs_namenode_properties:
  - { name: "dfs.permissions.superusergroup", value: "hadoop" }
  - { name: "dfs.namenode.name.dir", value: "/media/persistent0" }
hdfs_datanode_properties:
  - { name: "dfs.permissions.superusergroup", value: "hadoop" }
  - { name: "dfs.datanode.data.dir", value: "{{ hdfs_disks | map(attribute='mount_point') | join(',') }}" }
