# Copyright 2016(c) The Ontario Institute for Cancer Research. All rights reserved.

- name: Clean copy
  file: path="{{ install_dir }}"
        state=absent

- name: Ensure directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ install_dir }}"

- name: Download the distribution
  get_url:  url="{{ download_dist_url }}"
            dest="{{ staging_dir }}/{{ download_dist_filename }}"
            mode=0444

- name: Extract the dist
  unarchive:  src="{{ staging_dir }}/{{ download_dist_filename }}"
              dest="{{ install_dir }}"
              copy=no

- name: Update the symbolic link to the distribution
  file: path="{{ download_home }}"
        src="{{ install_dir }}/{{ download_dist_fullname }}"
        state=link
        force=yes

- name: Copy application.yml
  template: src=application.yml.j2 dest="{{ download_conf }}/application.yml" mode=644 force=yes