# Copyright 2015(c) The Ontario Institute for Cancer Research. All rights reserved.

- name: Set kernel shared memory
  sysctl: name=kernel.shmmax 
          value=17179869184
          state=present
  register: shmmax

- name: Set kerel shared memory
  sysctl: name=kernel.shmall 
          value=4194304
          state=present
  register: shmall

