- name: Install development header files
  apt:  pkg={{ item }} 
        state=installed 
        update_cache=yes
  with_items:
    - python-software-properties
    - libpq-dev
    - python-pip
    - python-psycopg2


- name: Add repository key
  apt_key: data="{{ lookup('file', 'ACCC4CF8.asc') }}"  
           state=present

- name: Add PostgreSQL repository
  apt_repository: repo="{{ postgresql_repo }}" 
                  state=present

- name: Install postgresql
  apt:  pkg="postgresql-{{ postgresql_version }}" 
        state=installed 
        update_cache=yes

- name: Install PostgreSQL config file
  copy: src=postgresql.conf 
        dest=/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf 
        force=yes

- name: Install PostgreSQL hba file
  copy: src=pg_hba.conf 
        dest=/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf 
        force=yes


- name: Set kernel shared memory
  sysctl: name=kernel.shmmax 
          value=17179869184 
          state=present
  register: shmmax

- name: Set kerel shared memory
  sysctl: name=kernel.shmall 
          value=4194304 
          state=present
  register: shmall

- name: Restart postgres server
  service: name=postgresql 
           state=restarted
  when: shmmax|changed or shmall|changed
