# Copyright 2015(c) The Ontario Institute for Cancer Research. All rights reserved.

# See http://stackoverflow.com/questions/18132719/how-to-change-elasticsearch-max-size
- name: Setting limits for elasticsearch_major_version < 5
  copy: src="limits.conf" dest="/etc/security/limits.d/elasticsearch.conf" mode=644 force=yes
  when:  elasticsearch_major_version < "5"

- name: Setting limits for elasticsearch_major_version >= 5 
  copy: src="limits.conf" dest="/etc/security/limits.conf" mode=644 force=yes
  when:  elasticsearch_major_version >= "5"

- name: Setting limits
  lineinfile: dest="/etc/pam.d/common-session" line="session required pam_limits.so"

- name: Copy over elasticsearch.yml.j3 conf for version - {{ elasticsearch_version }}
  template: src="elasticsearch.yml.j2" dest="/etc/elasticsearch/elasticsearch.yml" mode=644 force=yes
  when: elasticsearch_major_version < "5"

- name: Copy over elasticsearch5.yml.j3 conf for version - {{ elasticsearch_version }}
  template: src="elasticsearch5.yml.j2" dest="/etc/elasticsearch/elasticsearch.yml" mode=644 force=yes
  when: elasticsearch_major_version >= "5"

# FIXME: Maybe it is best to bite the bullet and just copy the entire config
- name: Patch elasticsearch init.d
  lineinfile: dest="/etc/default/elasticsearch" regexp="^#ES_HEAP_SIZE" line="ES_HEAP_SIZE=4g"

- name: Patch elasticsearch init.d to add jdk location 
  lineinfile: dest="/etc/init.d/elasticsearch" regexp="^JDK_DIRS=" line="JDK_DIRS=\"/usr/lib/jvm/jdk\""

- name: Restart ElasticSearch
  service: name=elasticsearch state=restarted

