# Copyright 2015(c) The Ontario Institute for Cancer Research. All rights reserved.

# See http://stackoverflow.com/questions/18132719/how-to-change-elasticsearch-max-size
- name: Setting limits
  copy: src="limits.conf" dest="/etc/security/limits.conf" mode=644 force=yes

- name: Setting limits
  copy: src="limits.conf" dest="/etc/security/limits.d/elasticsearch.conf" mode=644 force=yes

- name: Copy over elasticsearch conf
  template: src="elasticsearch.yml.j2" dest="/etc/elasticsearch/elasticsearch.yml" mode=644 force=yes

# FIXME: Maybe it is best to bite the bullet and just copy the entire config
- name: Patch elasticsearch init.d
  lineinfile: dest="/etc/init.d/elasticsearch" regexp="^#ES_HEAP_SIZE" line="ES_HEAP_SIZE=4g"

- name: Patch elasticsearch init.d to add jdk location 
  lineinfile: dest="/etc/init.d/elasticsearch" regexp="^JDK_DIRS=" line="JDK_DIRS=\"/usr/lib/jvm/jdk\""

#- name: Patch elasticsearch yml
#  lineinfile: dest="/etc/elasticsearch/elasticsearch.yml" regexp="bootstrap.mlockall" line="bootstrap.mlockall:true"

- name: Restart Elastic search
  service: name=elasticsearch state=restarted

