# Copyright 2015(c) The Ontario Institute for Cancer Research. All rights reserved.


- name: Fetch Elasticsearch for {{ elasticsearch_version }} using url - {{ elasticsearch_download }}
  get_url: url={{ elasticsearch_download }}/{{ elasticsearch_package }} dest=/tmp  mode=644
  when: elasticsearch_major_version < "5"  

- name: Fetch Elasticsearch for {{ elasticsearch_version }} using url - {{ elasticsearch_download2 }}
  get_url: url={{ elasticsearch_download2 }}/{{ elasticsearch_package }} dest=/tmp  mode=644
  when: elasticsearch_major_version >= "5"  

- name: Install Elasticsearch package
  shell: dpkg -i -E --force-depends "/tmp/{{ elasticsearch_package }}"

- name: Create path.data directories - "{{ elasticsearch_path_data }}"
  become: yes
  shell: mkdir -p "{{ elasticsearch_path_data }}/nodes"
  
- name: Create path.log directories - "{{ elasticsearch_path_log }}"
  become: yes
  shell: mkdir -p "{{ elasticsearch_path_log }}"

- name: make sure Elasticsearch is enabled and started
  service: name=elasticsearch enabled=yes state=started
