# Copyright 2015(c) The Ontario Institute for Cancer Research. All rights reserved.

- include: install.yml tags=elasticsearch-install
- include: configure.yml tags=elasticsearch-configure
- include: plugins.yml tags=elasticsearch-plugins






