- name: Creating script dir
  file: dest="/tmp/scripts" state="directory"

- name: Copy identifier script
  copy: src="{{ item }}" dest="/tmp/scripts/{{ item }}" mode=0744
  with_items:
    - "portal_schema.sql"
 
- name: Create identifier database
  postgresql_db: name="dcc_portal" state=present

- name: Create DCC User
  postgresql_user: db="dcc_portal" name="dcc" login_password="dcc"

# Explicit set password, otherwise have to use hash above
- name: Set password
  shell: psql -d dcc_portal -c "ALTER USER dcc with PASSWORD 'dcc'"
  ignore_errors: yes

- name: Initialize identifier
  command: psql -d dcc_portal -f {{ item }}
  with_items:
    - "/tmp/scripts/portal_schema.sql"
