portal_root: "/srv"

################################################################################
# DCC Portal 
################################################################################
es_index_name: "openstack-test"






