---

- name: exeuting command
  debug: msg="python roles/hadoop_node/files/setup_host.py -p {{ ansible_ssh_private_key_file }} -c {{ hostvars['dcc-hadoop-manager']['cm_host'] }} -h {{ inventory_hostname }}"

- name: Setup Host using Cloudera Manager API
  sudo: no
  connection: local
  shell: "python roles/hadoop_node/files/setup_host.py -p {{ ansible_ssh_private_key_file }} -c {{ hostvars['dcc-hadoop-manager']['cm_host'] }} -h {{ inventory_hostname }}"
  delegate_to: localhost
  register: python_script

- name: output of setup_host
  debug: msg="{{ python_script.stdout }}"
