################################################################################
#
# Sets up a host as Hadoop client : 
#
# - Adds the host to hadoop cluster and sets it up as gateway for various services.
#
# 
# TODO: 
#     - Parametrize cluster state check.
#     - Parametrize the hardcoded "dcc-etl-main" hostname.
#
################################################################################

- name: Check Cluster State
  command:  curl -u 'admin:admin' localhost:7180/api/v9/hosts
  register: cluster_output
  ignore_errors: yes

- include: setup_node.yml
  when: cluster_output.stdout.find('dcc-etl-main') == -1
