# TODO: parametrize install location /usr/lib/jvm/jdk.

- name: Make sure openjdk is uninstalled
  apt: pkg=openjdk state=absent purge=true

- name: Make a directory that holds the Java binaries
  file: path=/usr/lib/jvm state=directory

- name: Download JDK
  command: "wget --max-redirect=2 --header 'Cookie: oraclelicense=accept-securebackup-cookie' '{{ jdk_download_url }}' chdir=/tmp creates=/tmp/{{ jdk_download_filename }}"

- name: Unpack the compressed JDK binaries
  command: tar -xvzf /tmp/{{ jdk_download_filename }} chdir=/usr/lib/jvm creates=/usr/lib/jvm/jdk{{ jdk_version }}

- name: Update the symbolic link to the JDK install
  file: path=/usr/lib/jvm/jdk src=/usr/lib/jvm/jdk{{ jdk_version }} state=link force=yes

- name: Add the JDK binaries to the system path (/etc/profile)
  lineinfile: "dest={{ item.dest }} line={{ item.line }} state={{ item.state }}"
  with_items:
    - { dest: '/etc/profile', regexp: '^JAVA_HOME=/usr/lib/jvm/jdk', line: 'JAVA_HOME=/usr/lib/jvm/jdk', state: 'present' }
    - { dest: '/etc/profile', regexp: '^PATH=.*JAVA_HOME.*', line: 'PATH=$PATH:$HOME/bin:$JAVA_HOME/bin', state: 'present' }

- name: Inform the system where JDK is located
  command: "{{ item }}"
  with_items:
    - update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/jdk/bin/java" 1
    - update-alternatives --install "/usr/bin/javac" "javac" "/usr/lib/jvm/jdk/bin/javac" 1
    - update-alternatives --install "/usr/bin/javaws" "javaws" "/usr/lib/jvm/jdk/bin/javaws" 1
    - update-alternatives --install "/usr/bin/javah" "javah" "/usr/lib/jvm/jdk/bin/javah" 1
    - update-alternatives --install "/usr/bin/jar" "jar" "/usr/lib/jvm/jdk/bin/jar" 1

- name: Inform the system that JDK must be the default
  command: "{{ item }}"
  with_items:
    - update-alternatives --set java /usr/lib/jvm/jdk/bin/java
    - update-alternatives --set javac /usr/lib/jvm/jdk/bin/javac
    - update-alternatives --set javaws /usr/lib/jvm/jdk/bin/javaws
    - update-alternatives --set javah /usr/lib/jvm/jdk/bin/javah
    - update-alternatives --set jar /usr/lib/jvm/jdk/bin/jar
