# Copyright 2015(c) The Ontario Institute for Cancer Research. All rights reserved.

- name: Make sure openjdk is uninstalled
  apt: pkg=openjdk state=absent purge=true

- name: Make a directory that holds the Java binaries
  file: path={{ java_install_dir }} state=directory

- name: Download JDK
  command: "wget --max-redirect=2 --header 'Cookie: oraclelicense=accept-securebackup-cookie' '{{ jdk_download_url }}' chdir=/tmp creates=/tmp/{{ jdk_download_filename }}"

- name: Unpack the compressed JDK binaries
  command: tar -xvzf /tmp/{{ jdk_download_filename }} chdir={{ java_install_dir }} creates={{ java_install_dir }}/jdk{{ jdk_version }}

- name: Update the symbolic link to the JDK install
  file: path={{ item }} 
        src="{{ java_install_dir }}/jdk{{ jdk_version }}"
        state=link 
        force=yes
  with_items:
    - "{{ java_install_dir }}/jdk"

- name: Add the JDK binaries to the system path (/etc/profile)
  lineinfile: "dest={{ item.dest }} line={{ item.line }} state={{ item.state }}"
  with_items:
    - { dest: '/etc/profile', regexp: '^JAVA_HOME={{ java_install_dir }}/jdk', line: 'JAVA_HOME={{ java_install_dir }}/jdk', state: 'present' }
    - { dest: '/etc/profile', regexp: '^PATH=.*JAVA_HOME.*', line: 'PATH=$PATH:$HOME/bin:$JAVA_HOME/bin', state: 'present' }

- name: Inform the system where JDK is located
  command: "{{ item }}"
  with_items:
    - update-alternatives --install "/usr/bin/java" "java" "{{ java_install_dir }}/jdk/bin/java" 1
    - update-alternatives --install "/usr/bin/javac" "javac" "{{ java_install_dir }}/jdk/bin/javac" 1
    - update-alternatives --install "/usr/bin/javaws" "javaws" "{{ java_install_dir }}/jdk/bin/javaws" 1
    - update-alternatives --install "/usr/bin/javah" "javah" "{{ java_install_dir }}/jdk/bin/javah" 1
    - update-alternatives --install "/usr/bin/jar" "jar" "{{ java_install_dir }}/jdk/bin/jar" 1

- name: Inform the system that JDK must be the default
  command: "{{ item }}"
  with_items:
    - update-alternatives --set java {{ java_install_dir }}/jdk/bin/java
    - update-alternatives --set javac {{ java_install_dir }}/jdk/bin/javac
    - update-alternatives --set javaws {{ java_install_dir }}/jdk/bin/javaws
    - update-alternatives --set javah {{ java_install_dir }}/jdk/bin/javah
    - update-alternatives --set jar {{ java_install_dir }}/jdk/bin/jar
