# TODO: parametrize install location /usr/java/jdk.

- name: Make sure openjdk is uninstalled
  apt: pkg=openjdk state=absent purge=true

- name: Make required directories
  file: path={{ item }} state=directory
  with_items:
    - /usr/java

- name: Download JDK
  command: "wget --max-redirect=2 --header 'Cookie: oraclelicense=accept-securebackup-cookie' '{{ jdk_download_url }}' chdir=/tmp creates=/tmp/{{ jdk_download_filename }}"

- name: Unpack the compressed JDK binaries
  command: tar -xvzf /tmp/{{ jdk_download_filename }} chdir=/usr/java creates=/usr/java/jdk{{ jdk_version }}

- name: Update the symbolic link to the JDK install
  file: path={{ item }} 
        src=/usr/java/jdk{{ jdk_version }} 
        state=link 
        force=yes
  with_items:
    - /usr/java/jdk
    - /usr/java/default

- name: Add the JDK binaries to the system path (/etc/profile)
  lineinfile: "dest={{ item.dest }} line={{ item.line }} state={{ item.state }}"
  with_items:
    - { dest: '/etc/profile', regexp: '^JAVA_HOME=/usr/java/jdk', line: 'JAVA_HOME=/usr/java/jdk', state: 'present' }
    - { dest: '/etc/profile', regexp: '^PATH=.*JAVA_HOME.*', line: 'PATH=$PATH:$HOME/bin:$JAVA_HOME/bin', state: 'present' }

- name: Inform the system where JDK is located
  command: "{{ item }}"
  with_items:
    - update-alternatives --install "/usr/bin/java" "java" "/usr/java/jdk/bin/java" 1
    - update-alternatives --install "/usr/bin/javac" "javac" "/usr/java/jdk/bin/javac" 1
    - update-alternatives --install "/usr/bin/javaws" "javaws" "/usr/java/jdk/bin/javaws" 1
    - update-alternatives --install "/usr/bin/javah" "javah" "/usr/java/jdk/bin/javah" 1
    - update-alternatives --install "/usr/bin/jar" "jar" "/usr/java/jdk/bin/jar" 1

- name: Inform the system that JDK must be the default
  command: "{{ item }}"
  with_items:
    - update-alternatives --set java /usr/java/jdk/bin/java
    - update-alternatives --set javac /usr/java/jdk/bin/javac
    - update-alternatives --set javaws /usr/java/jdk/bin/javaws
    - update-alternatives --set javah /usr/java/jdk/bin/javah
    - update-alternatives --set jar /usr/java/jdk/bin/jar
