# Copyright 2015(c) The Ontario Institute for Cancer Research. All rights reserved.

- name: Install add-apt-repostory
  become: yes
  apt: name=software-properties-common state=latest

- name: Add Oracle Java Repository
  become: yes
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java 8 License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default

- name: Set JAVA_HOME system wide
  lineinfile: "dest=/etc/environment state=present regexp=^JAVA_HOME line=JAVA_HOME={{ jdk_home }}"

- name: Add the JAVA_HOME to the system environment (/etc/profile)
  lineinfile:
    dest: /etc/profile
    regexp: ^export JAVA_HOME
    line: export JAVA_HOME={{ jdk_home }}