---
# file: roles/jdk/tasks/main.yml

- name: Install python software properties (apt-add-repository)
  apt: pkg=python-software-properties update_cache=yes

- name: Add Java PPA
  apt_repository: repo=ppa:webupd8team/java state=present

- name: Automatically accept Java license
  shell: echo "{{ java_name }}-installer" shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  changed_when: False

- name: install or update Oracle Java 7 JDK via apt
  apt: pkg={{ item }} update_cache=yes state=latest install_recommends=yes
  with_items:
    - oracle-java7-installer
    - oracle-java7-set-default

