- name: Install python software properties (apt-add-repository)
  apt: pkg=python-software-properties update_cache=yes

- name: Add Java PPA
  apt_repository: repo=ppa:webupd8team/java state=present

- name: Automatically accept Java license
  shell: echo "{{ java_name }}-installer" shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  changed_when: False

- name: Install Java
  apt: pkg='{{ item }}' state=present update_cache=yes force=yes
  with_items:
    - "{{ java_name }}-installer"
    - "{{ java_name }}-set-default"
