################################################################################
# Load knapsack compatible archives
# This assumes that the elastic search instances are up!
################################################################################

- name: Drop index
  shell: "curl -XDELETE localhost:9200/{{ es_index_name }}/"
  ignore_errors: yes


- name: Upload archives to host
  copy: src="{{ archive_dir }}/{{ archive_prefix }}-{{ item }}.tar.gz" dest="/tmp/{{ item }}.tar.gz" mode=644
  with_items:
    - release
    - project-text
    - project
    - pathway-text
    - pathway
    - donor-text
    - donor
    - donor-centric
    - gene-text
    - gene
    - gene-centric
    - mutation-text
    - mutation-centric
    - observation-centric


# FIXME: We don't know when this finishes 
- name: Use knapack to import
  shell: "curl -XPOST http://localhost:9200/{{ es_index_name }}/_import?target=/tmp/{{ item }}&millis=30000"
  with_items:
    - release
    - project-text
    - project
    - pathway-text
    - pathway
    - donor-text
    - donor
    - donor-centric
    - gene-text
    - gene
    - gene-centric
    - mutation-text
    - mutation-centric
    - observation-centric

