# Copyright 2015(c) The Ontario Institute for Cancer Research. All rights reserved.
#
# Description:
#   Setup Task: 
#     Creates the instances defined in inventory file using create-openstack-instances task.
#     Creates and uploads the host file for above instances to all hosts

- name: Create debug file
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Remove previous debug file if exist"
      shell: echo "public_ip \t hostname \t private_ip \t group " > {{ group }}_bootstrap_hosts_debug
      delegate_to: localhost

- name: Creates OpenStack instances of all the hosts in group parameter, defined in hosts file.
  hosts: "{{ group }}"
  user: root
  gather_facts: no
  serial: 1
  vars_files:
    - "../vars/main.yml"
  tasks:
    - include: create-os-servers.yml
        
    - name: Writing some debug information about hosts
      shell: echo "{{ ip_data.floating_ip.floating_ip_address }} \t {{ inventory_hostname }} \t {{ inventory_hostname | regex_replace('^[a-z]*-([a-z]*-?\w*)(-\d*$)?', '\\1') | replace("-", "_") }}" >> {{ group }}_bootstrap_hosts_debug
      delegate_to: localhost