# Copyright 2015(c) The Ontario Institute for Cancer Research. All rights reserved.

cli_name: dcc-etl-cli
cli_jar_filename: "{{ cli_name }}-{{ cli_version }}.jar"
cli_url: "{{ artifactory_snapshot_url }}/{{ artifactory_dcc_path }}/{{ cli_name }}/{{ cli_version }}/{{ cli_jar_filename }}"

annotator_jar_name: dcc-etl-annotator
annotator_jar_filename: "{{ annotator_jar_name }}-{{ annotator_version }}.jar"
annotator_jar_url: "{{ artifactory_snapshot_url }}/{{ artifactory_dcc_path }}/{{ annotator_jar_name }}/{{ annotator_version }}/{{ annotator_jar_filename }}"

keys_dir: "{{ etl_home }}/keys" 
config_dir: "{{ etl_home }}/conf"
config_project_dir: "{{ config_dir }}/projects"
config_dictionaries_dir: "{{ config_dir }}/dictionaries"
jobs_dir: "{{ etl_home }}/jobs"
lib_dir: "{{ etl_home }}/lib"
overarch_dir: "{{ repo_dir}}/dcc-etl-cli/src/main/scripts/overarch"
lisi_facade: "{{ overarch_dir}}/facades/lisi-facade.sh"
