################################################################################
#
# Sets up a Hadoop client:
#
# TODO: 
#     - Parametrize the hardcoded "dcc-hadoop-manager".
#
################################################################################

- name: Assign command to variable
  set_fact: command="python roles/hadoop_cluster/files/setup_cluster.py -p {{ ansible_ssh_private_key_file }} -c {{ hostvars['dcc-hadoop-manager']['cm_host'] }} "

- name: Provision Hadoop Cluster using Cloudera Manager API
  sudo: no
  connection: local
  shell: "{{ command }}"
  delegate_to: localhost
  register: python_script

- name: output of setup_cluster
  debug: msg="{{ python_script.stdout }}"
