# Copyright 2015(c) The Ontario Institute for Cancer Research. All rights reserved.

- name: Set python script variable
  set_fact: python_script="roles/hadoop_cluster/files/setup_cluster.py"

- name: Read embedded postgres password from Manager host
  sudo: yes
  shell:  "grep REPORTSMANAGER.db.password /etc/cloudera-scm-server/db.mgmt.properties | rev | cut -d= -f1 | rev"
  register: rman_pass

- name: Remove previous setup script
  local_action: "command rm -f {{ python_script }}"
  sudo: no

- name: Populate setup script with variables
  local_action: template dest={{ python_script }} src={{ python_script }}.j2
  sudo: no

- name: Provision Hadoop Cluster using Cloudera Manager API
  sudo: no
  connection: local
  shell: "python {{ python_script }}"
  delegate_to: localhost
  register: output

- name: output of setup_cluster
  debug: msg="{{ output.stdout }}"
