elasticsearch_version: 0.90.1
elasticsearch_package: elasticsearch-{{ elasticsearch_version }}.deb
elasticsearch_download: https://download.elasticsearch.org/elasticsearch/elasticsearch
es_cluster_name: elasticsearch
