# Copyright 2014(c) The Ontario Institute for Cancer Research. All rights reserved.

# dcc_portal
server_name: dcc.icgc.org

# nginx.conf
worker_processes: 4
worker_connections: 768
portal_port: 5381
