# Jerry said the snpeff directory name is dependent on the reference genome name

annotator_root: "/u/dcc_dev/dcc-annotator"
annotator_snpeff_dir:  "{{ annotator_root }}/data/snpeff/GRCh37.75"
annotator_reference_dir: "{{ annotator_root }}/data/genome"

annotator_import_fs: LOCAL
annotator_export_fs: LOCAL
annotator_work_dir: "/tmp/work"

snpeff_version: 3.3-GRCh37.75
snpeff_name: dcc-snpeff
snpeff_archive: "{{ snpeff_name }}-{{ snpeff_version }}.bin"
snpeff_url: "{{ artifactory_deps_url }}/org/icgc/dcc/{{ snpeff_name }}/{{ snpeff_version }}/{{ snpeff_archive }}"
