job_tracker: "{{ server_prefix }}-etl-worker-01:8021"
default_fs: "hdfs://{{ server_prefix }}-etl-worker-01"
postgresql_uri: "jdbc:postgresql://{{ server_prefix }}-etl-postgres/fathmm?user=dcc&password=dcc"
mongo_base_uri: "mongodb://{{ server_prefix }}-etl-mongo"
identifier_uri: "http://{{ server_prefix }}-etl-identifier:6381"
elasticsearch_uri: "es://{{ server_prefix }}-etl-elasticsearch:9300"
name_node: "hdfs://{{ server_prefix }}-etl-worker-01:8020"
zookeeper_quorum: "{{ server_prefix }}-etl-worker-01"
env:
      HADOOP_USER_NAME: hdfs