# Copyright 2016(c) The Ontario Institute for Cancer Research. All rights reserved.

- name: Install dependencies
  sudo: yes
  apt: name=software-properties-common state=latest

- name: Add JDK8 Repository
  sudo: yes
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Oracle Java License
  sudo: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Java
  sudo: yes
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default

