- include: tasks/setup.yml group=elasticsearch

- hosts: elasticsearch
  gather_facts: no
  sudo: yes
  vars_files:
    - "vars/main.yml"
  roles: 
    - { role: elasticsearch, tags: [ 'elasticsearch' ] }