---
# file: etl-main.yml

- hosts: etl-main
  gather_facts: True
  sudo: yes
  vars_files:
    - "vars/main.yml"

  roles: 
    - lzo
    - mongodb
    - etl
    - annotator
    - exporter
    - downloader
