# Copyright 2016(c) The Ontario Institute for Cancer Research. All rights reserved.

- include: tasks/setup.yml group=hadoop-master:hadoop-worker:id-group:etl
- include: tasks/setup-existing.yml group=hadoop-master:hadoop-worker:id-group:etl


# HDFS - Namenode
- hosts: hadoop_master
  become: yes
  vars_files:
    - "vars/main.yml"
  roles:
    - { role: hdfs, hdfs_namenode: True }

# HDFS - Datanode    
- hosts: hadoop_worker
  become: yes
  vars_files:
  - "vars/main.yml"
  roles:
    - { role: hdfs, hdfs_namenode: False }


# Spark - Master
- hosts: hadoop_master
  become: yes
  vars_files:
    - "vars/main.yml"
  roles:
    - { role: spark, master: True }

# Spark - Slave    
- hosts: hadoop_worker
  become: yes
  vars_files:
  - "vars/main.yml"
  roles:
    - { role: spark, master : False }

# Id Postgres Server
- name: Provision download server with postgres
  hosts: id_server
  gather_facts: no
  become: yes
  vars_files:
    - "vars/main.yml"
  roles:
    - postgres

# Configure Postgres
- name: Configure Postgres
  hosts: id_server
  gather_facts: no
  become: yes
  become_user: postgres
  vars_files:
    - "vars/main.yml"
  roles:
    - id_db

# Id Server
- name: Install ID Server
  hosts: id_server
  gather_facts: no
  become: yes
  vars_files:
    - "vars/main.yml"
  roles:
    - id

- name: Provision Mongodb server
  hosts: etl_server
  gather_facts: no
  become: yes
  vars_files:
    - "vars/main.yml"
  roles: 
    - mongodb

- name: Provision Import and Release
  hosts: etl_server
  gather_facts: no
  become: yes
  vars_files:
    - "vars/main.yml"
  roles: 
    - import
    - release
