# Copyright 2015(c) The Ontario Institute for Cancer Research. All rights reserved.
#
# Description:
#   ETL playbook
#     Provision ElasticSearch server
#     Provision Postgresql server
#     Seed Postgresql server with ICGC schemas
#     Provision DCC Identifier
#     Provision MongoDB server
#     Provision ETL Worker Nodes
#     Provision Cloudera Manager
#     Provision ETL Main Node#
#
#   Post provisioning steps: Do these before starting an ETL run 
#     Copy projects' submission files to hdfs
#     Create project.json configuration
#     Download the dictionary for the ETL run
#     Download codelist for the ETL run??

- include: tasks/setup.yml group=etl

- hosts: elasticsearch
  gather_facts: no
  sudo: yes
  vars_files:
    - "vars/main.yml"
  roles: 
    - { role: elasticsearch, tags: [ 'elasticsearch' ] }

- hosts: postgres
  gather_facts: no
  sudo: yes
  vars_files:
    - "vars/main.yml"
  roles: 
    - postgres

- hosts: postgres
  gather_facts: no
  sudo_user: postgres
  sudo: yes
  vars_files:
    - "vars/main.yml"
  roles: 
    - identifier_db

- hosts: identifier
  gather_facts: no
  sudo: yes
  vars_files:
    - "vars/main.yml"
  roles: 
    - identifier

- hosts: mongo
  gather_facts: no
  sudo: yes
  vars_files:
    - "vars/main.yml"
  roles: 
    - mongodb

- hosts: hadoop_worker
  gather_facts: no
  sudo: yes
  vars_files:
    - "vars/main.yml"
  roles: 
    - worker

- hosts: hadoop_manager
  gather_facts: no
  sudo: yes
  vars_files:
    - "vars/main.yml"
  roles:
    - hadoop_cluster

- hosts: etl_main
  gather_facts: no
  sudo: yes
  vars_files:
    - "vars/main.yml"
  roles:
    - hadoop_node 
    - mongodb
    - etl
    - annotator
    - exporter
    - hdfs_fuse
