################################################################################
#
# ETL playbook
#
# - Provision ElasticSearch server
# - Provision Postgresql server
# - Seed Postgresql server with ICGC schemas
# - Provision DCC Identifier
# - Provision MongoDB server
# - Provision ETL Worker Nodes
# - Provision Cloudera Manager
# - Provision ETL Main Node#
#
#
# Post provisioning steps: Do these before starting an ETL run 
#
# - Copy projects' submission files to hdfs
# - Create project.json configuration
# - Download the dictionary for the ETL run
# - Download codelist for the ETL run??
# 
################################################################################

- include: tasks/setup.yml group=etl

- hosts: etl_elasticsearch
  gather_facts: no
  sudo: yes
  vars_files:
    - "vars/main.yml"
  roles: 
    - elasticsearch

- hosts: etl-postgres
  gather_facts: no
  sudo: yes
  vars_files:
    - "vars/main.yml"

  roles: 
    - postgres

- hosts: etl_postgres
  gather_facts: no
  sudo_user: postgres
  sudo: yes
  vars_files:
    - "vars/main.yml"

  roles: 
    - postgres_seed

- hosts: etl_identifier
  gather_facts: no
  sudo: yes
  vars_files:
    - "vars/main.yml"

  roles: 
    - identifier

- hosts: etl_mongo
  gather_facts: no
  sudo: yes
  vars_files:
    - "vars/main.yml"

  roles: 
    - mongodb

- hosts: hadoop_worker
  gather_facts: False
  sudo: yes
  vars_files:
    - "vars/main.yml"

  roles: 
    - worker
    - lzo

- hosts: cloudera_manager
  gather_facts: no
  sudo: yes
  vars_files:
    - "vars/main.yml"

  roles:
    - cloudera_manager

- hosts: etl_main
  gather_facts: no
  sudo: yes
  vars_files:
    - "vars/main.yml"

  roles: 
    - lzo
    - mongodb
    - etl
    - annotator
    - exporter
    - downloader
