# Copyright 2014(c) The Ontario Institute for Cancer Research. All rights reserved.

- name: Provision Elasticsearch 5.0.0
  hosts: ga4gh-cluster
  gather_facts: no
  sudo: yes
  vars:
    elasticsearch_version: 5.0.0
    es_cluster_name: ga4gh-elasticsearch
  roles: 
    - elasticsearch

