# Copyright 2016(c) The Ontario Institute for Cancer Research. All rights reserved.

- include: tasks/setup.yml group=hadoop-master:hadoop-worker
- include: tasks/setup-existing.yml group=hadoop-master:hadoop-worker

# HDFS - Namenode
- hosts: hadoop-master
  become: yes
  vars_files:
    - "vars/main.yml"
  roles:
    - { role: hdfs, hdfs_namenode: True }

# HDFS - Datanode    
- hosts: hadoop-worker
  become: yes
  vars_files:
  - "vars/main.yml"
  roles:
    - { role: hdfs, hdfs_namenode: False }
