---
# Copyright 2014(c) The Ontario Institute for Cancer Research. All rights reserved.

- include: tasks/setup.yml group=portal

- name: Configure and deploy varnish
  hosts: varnish
  gather_facts: no
  user: ubuntu
  sudo: yes

  roles:
    - varnish

- name: Configure and deploy nginx
  hosts: nginx
  gather_facts: no
  user: ubuntu
  sudo: yes

  roles:
    - nginx

- name: Configure and deploy portal
  hosts: portal-main
  gather_facts: no
  user: ubuntu
  sudo: yes

  roles:
    - portal
