# Copyright 2016(c) The Ontario Institute for Cancer Research. All rights reserved.

#- include: tasks/setup.yml group=hdfs-namenode:hdfs-datanode:submission
- include: tasks/setup-existing.yml group=hdfs-namenode:hdfs-datanode:submission

# HDFS - NameNode    
- hosts: hadoop_master
  become: yes
  vars_files:
    - "vars/main.yml"
  roles:
    - { role: hdfs, hdfs_namenode: True }

# HDFS - DataNode    
- hosts: hadoop_worker
  become: yes
  vars_files:
  - "vars/main.yml"
  roles:
    - { role: hdfs, hdfs_namenode: False }


# Hadoop - JobTracker    
- hosts: hadoop_master
  become: yes
  vars_files:
    - "vars/main.yml"
  roles:
    - { role: hadoop-mapreduce, jobtracker: True }

# Hadoop - TaskTracker    
- hosts: hadoop_worker
  become: yes
  vars_files:
  - "vars/main.yml"
  roles:
    - { role: hadoop-mapreduce, jobtracker: False }

- hosts: submission
  gather_facts: no
  sudo: yes
  vars_files:
    - "vars/main.yml"
  roles: 
    - mongodb
    - submission
