################################################################################
#
# Submission playbook
# 1) Instances
# 2) CDH Manager
# 3) MongoDB
# 4) Submission Node
#
# TODO
#   - System (.system) need to be set in place
#   - Need to clear root_dir on HDFS
#   - Better injection of mongo_uri, job_tracker
#
# Hacks
#   - Codelists and Dictionary should not use /ws/seed
#   
#
################################################################################

- include: tasks/setup.yml group=submission
- include: tasks/submission-cm.yml
- include: tasks/submission-mongo.yml
- include: tasks/submission-main.yml

