# Copyright 2015(c) The Ontario Institute for Cancer Research. All rights reserved.
#
# Description:
#   Submission playbook
#     1) Instances
#     2) CDH Manager
#     3) MongoDB
#     4) Submission Node
#
# TODO:
#   - System (.system) need to be set in place
#   - Need to clear root_dir on HDFS
#
# Hacks:
#   - Codelists and Dictionary should not use /ws/seed

- include: tasks/setup.yml group=submission

- hosts: hadoop_worker
  gather_facts: no
  sudo: yes
  vars_files:
    - "vars/main.yml"
  roles: 
    - jdk

- hosts: hadoop_manager
  gather_facts: no
  sudo: yes
  vars_files:
    - "vars/main.yml"
  roles:
    - hadoop_cluster

- hosts: mongo
  gather_facts: no
  sudo: yes
  vars_files:
    - "vars/main.yml"
  roles: 
    - mongodb

- hosts: submission_main
  gather_facts: no
  sudo: yes
  vars_files:
    - "vars/main.yml"
  roles: 
    - mongodb
    - submission
