################################################################################
#
# Submission playbook
# 1) Instances
# 2) CDH Manager
# 3) MongoDB
# 4) Submission Node
#
# TODO
#   - System (.system) need to be set in place
#   - Need to clear root_dir on HDFS
#   - Better injection of mongo_uri, job_tracker
#
# Hacks
#   - Codelists and Dictionary should not use /ws/seed
#   
#
################################################################################

- include: tasks/setup.yml group=submission

- hosts: submission_cm
  gather_facts: yes
  sudo: yes
  vars_files:
    - "vars/main.yml"

  roles: 
    - cloudera_manager

- hosts: submission_mongo
  gather_facts: yes
  sudo: yes
  vars_files:
    - "vars/main.yml"

  roles: 
    - mongodb

- hosts: submission_main
  gather_facts: yes
  sudo: yes
  vars_files:
    - "vars/main.yml"

  roles: 
    - mongodb
    - submission
